### ISSUE TITLE
[docs] New page - badge

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#512] opened 2022-09-02 19:27 UTC
XD link: https://xd.adobe.com/view/b9ff51f7-08cd-4e68-b290-a64601198600-ecac/

**Comment by coreyvickery** [comment] 2023-06-13 08:19
Duplicate of [#923](https://github.com/RedHat-UX/red-hat-design-system/issues/923), so closing.

**Closed by coreyvickery** 2023-06-13 08:19 UTC
Labels: documentation, for design
