### ISSUE TITLE
[bug] local dev server no longer finding and redirecting demo assets 

### ISSUE THREAD

**Issue by eyevana** [RedHat-UX/red-hat-design-system#955] opened 2023-04-26 11:27 UTC
### Describe the bug

Not sure if I should open this bug here or in pfe, but I think we need to account for the fact that our demo assets are no longer coming from `/components` in the redirect rules in Pfe's dev server config. 

### Which Component?

All

### Steps to reproduce

To reproduce, spin up a local dev server and go to one of the component demos:

http://localhost:8000/elements/alert/demo/

Open the network tab, and you'll see the assets that are 404ing, for example:

http://localhost:8001/elements/alert/demo/demo.css

...which should actually be redirecting to:

http://localhost:8001/elements/rh-alert/demo/demo.css

### Expected behaviour

Demos should work as expected in our local dev environment

### Screenshots

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/55894965/234561236-d4c8fa50-0346-4a20-9544-2bda31dfbea4.png">

### Operating System (OS)

macOS

### Browser

Chrome

**Comment by zeroedin** [comment] 2023-04-26 12:15
@eyevana I believe this is what you are looking for.  https://github.com/patternfly/patternfly-elements/pull/2464

If you want we can sync on this issue and have you help test.  I need to write a change set for that and get it out for review.  Please do feel free to look over the changes and give any feedback.

**Comment by zeroedin** [comment] 2023-04-26 13:13
Also duplicate of https://github.com/RedHat-UX/red-hat-design-system/issues/885

**Comment by eyevana** [comment] 2023-04-26 13:37
Cool, cool. Thanks for looping me into these changes. I'll take a look
soon.

**Comment by zeroedin** [comment] 2023-06-20 14:12
This was closed with upgrade to @patternfly/pfe-tools@1.3.2

**Closed by zeroedin** 2023-06-20 14:12 UTC
Labels: bug
