### ISSUE TITLE
XD Template Development

### ISSUE THREAD

**Issue by ronniemcbride** [RedHat-UX/red-hat-design-system#395] opened 2022-06-15 13:33 UTC
### Discussed in https://github.com/orgs/RedHat-UX/discussions/352

<div type='discussions-op-text'>

<sup>Originally posted by **ronniemcbride** June  2, 2022</sup>
Objective: To drastically automate the documentation development process by templatizing a starter XD doc

**Feature request**
Create an XD template system that contains all the various section patterns that can be:
turned on and off.
Stacked and repositioned while maintaining spacing
Create a template that can be used by designers from outside teams. 

**Next steps**
Audit the current ux.redhat.com site
Meet with the design system team members to work out XD approach and implementation
Create a how-to-use document and  added to the team process documentation

**UX Designer Deliverable:**
Final  XD template & usage documentation
</div>

**Comment by coreyvickery** [comment] 2022-10-27 19:49
Duplicate of https://github.com/RedHat-UX/red-hat-design-system/issues/413, closing.

**Closed by coreyvickery** 2022-10-27 19:49 UTC
