### ISSUE TITLE
[docs] shortcode that renders all docs code tab sections for an array of elements

### ISSUE THREAD

**Issue by nikkimk** [RedHat-UX/red-hat-design-system#1073] opened 2023-06-16 13:18 UTC
### Description

For any given component, the code tab requires the same series of shortcodes. And for components with multiple custom elements, like accordion, footer, tabs, etc., that series repeats for every element which leave a lot of room for error:

```
## <element-tagname>
{% renderSlots for='element-tagname', level=3 %}{% endrenderSlots %}

{% renderAttributes for='element-tagname', level=3 %}{% endrenderAttributes %}

{% renderMethods for='element-tagname', level=3 %}{% endrenderMethods %}

{% renderEvents for='element-tagname', level=3 %}{% endrenderEvents %}

{% renderCssParts for='element-tagname', level=3 %}{% endrenderCssParts %}

{% renderCssCustomProperties for='element-tagname', level=3 %}{% endrenderCssCustomProperties %}
```

### Suggested solution

We should have a short code that takes a a single component or comma-separated list of components and generates the code about of each component in the list.

### Example API

`{% renderElementsCode for='rh-accordion, rh-accordion-heafer, rh-accoordion-panel', level=3 %}` or 
`{% renderElementsCode for='rh-cta', level=3 %}`

### Additional context

This was a discussion in [#1068](https://github.com/RedHat-UX/red-hat-design-system/pull/1068#pullrequestreview-1482073906).

**Comment by zeroedin** [comment] 2023-06-16 13:41
The only problem I can think of with doing this is when we want to customize some content for a specific section.  Right now each shortcode has an optional `content` area.    That would be nixed given these short codes.   However I am not sure at this moment we are doing that for any of these blocks off the top of my head.

**Comment by nikkimk** [comment] 2023-06-16 20:52
@zeroedin since these would be in addition to and not in replacement of, you could use the old shortcodes if you need to customize.

For example:
```
{% renderElementsCode for='rh-audio-player, rh-audio-player-about, rh-audio-player-profile', level=3 %}
## <rh-audio-player-subscribe>
{% renderSlots for='rh-audio-player-subscribe', level=3 %}
Custom stuff
{% endrenderSlots %}

{% renderAttributes for='rh-audio-player-subscribe', level=3 %}{% endrenderAttributes %}

More custom stuff

{% renderMethods for='rh-audio-player-subscribe', level=3 %}{% endrenderMethods %}

{% renderEvents for='rh-audio-player-subscribe', level=3 %}{% endrenderEvents %}

{% renderCssParts for='rh-audio-player-subscribe', level=3 %}{% endrenderCssParts %}

{% renderCssCustomProperties for='rh-audio-player-subscribe', level=3 %}{% endrenderCssCustomProperties %}
{% renderElementsCode for='rh-audio-player-transcript', level=3 %}
```

**Comment by bennypowers** [comment] 2023-06-26 09:53
is this a dupe of #1052?

**Comment by nikkimk** [comment] 2023-06-27 12:43
@bennypowers no but I could see how it would make sense that they be part of the same solution

**Closed** 2023-06-28 17:21 UTC
Labels: documentation
