### ISSUE TITLE
[bug] Broken images and missing headings on All Elements and All Patterns pages

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#890] opened 2023-04-04 13:26 UTC
### Describe the bug

- [ ] Fix broken images on [All Elements page](https://ux.redhat.com/elements/) and [All Patterns page](https://ux.redhat.com/patterns/)
- [ ] Add headings below each image on both pages

### Which Component?

n/a

### Steps to reproduce

See [All Elements page](https://ux.redhat.com/elements/) and [All Patterns page](https://ux.redhat.com/patterns/)

### Expected behaviour

Should be showing images and headings

### Operating System (OS)

macOS

**Comment by bennypowers** [comment] 2023-04-04 13:26
Is this a duplicate of #872 ?

**Comment by marionnegp** [comment] 2023-04-04 13:36
@bennypowers, images for footer, secondary nav, and primary nav are missing, so I don't think it's related.

**Closed** 2023-05-09 05:06 UTC
Labels: bug, documentation
