### ISSUE TITLE
[docs] Copy/paste missing or broken on Tokens pages

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#1169] opened 2023-07-26 13:24 UTC
The tables of tokens under all Tokens sections are missing copy/paste functionality in the right column.

See: https://ux.redhat.com/tokens/space/

<img width="960" alt="image" src="https://github.com/RedHat-UX/red-hat-design-system/assets/1890950/9d601ea8-587d-4a20-ae3f-2ea4b2985c47">

**Comment by bennypowers** [comment] 2023-07-26 13:26
this is a duplicate of #1146

**Comment by markcaron** [comment] 2023-07-26 13:27
@bennypowers #1146 looks like a larger effort. Is it possible to fix this as a smaller chunk quickly?

**Comment by bennypowers** [comment] 2023-07-26 15:27
#1166 already fixed this

**Closed** 2023-07-26 15:35 UTC
Labels: high priority
