### ISSUE TITLE
[spike] Explore `promo` variant / pattern capabilities in `<rh-card>`

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#1352] opened 2023-11-16 16:22 UTC
Explore the use of `<rh-card>` for the Promo "component" / pattern, since it seems that they're basically the same component with slight variations that could be achieved through simple pattern-based CSS (and perhaps an additional `promo` image slot).

<img width="923" alt="image" src="https://github.com/RedHat-UX/red-hat-design-system/assets/1890950/5ad3e2e4-5e4c-470d-a6b6-f1fc7f2b97ed">

![Screenshot 2023-11-28 at 12 44 28 PM](https://github.com/RedHat-UX/red-hat-design-system/assets/95588923/63704da8-787b-4b15-9e7f-ff268fe47516)

### Design files

- [Figma mockups / specs](https://www.figma.com/file/Bfdo9e0qzDx6quuMWYdi9K/Promo-(WIP)?type=design&node-id=0%3A1&mode=design&t=7T1jlObR6qQ2GSmp-1)
- [Discovery work](https://www.figma.com/file/UycR6PuwIy851tZ50WVKkq/Inline-promo---discovery?type=whiteboard&node-id=1%3A8649&t=hkkEYgqGWIDbqo3H-1)

**Comment by marionnegp** [comment] 2023-11-28 17:45
I added a screenshot of the standard inline promo as well, which might stretch card's pattern capabilities more than the featured inline promo.

**Comment by adamjohnson** [comment] 2024-05-16 14:25
This is a duplicate of #566 and is currently being worked on there.

**Closed by adamjohnson** 2024-05-16 14:25 UTC
Labels: feature, for dev, needs discovery, priority: high
