### ISSUE TITLE
[docs] playground CSS in ux.redhat.com

### ISSUE THREAD

**Issue by nikkimk** [RedHat-UX/red-hat-design-system#906] opened 2023-04-10 19:33 UTC
### Describe the bug

Elements displayed in playground do not have the same base.css applied that the demos do.

### Which Component?

rh-*

### Steps to reproduce

1. Use element inspector on https://ux.redhat.com/elements/accordion/#demos and scroll to the playground preview.
2. Use element inspector on https://ux.redhat.com/elements/accordion/demo/ 
3. Note that the fonts are different. (Demo is applies a demo.css that is not applied in playground.)

Issue is the same for other components as well.

### Expected behaviour

Demo and playground should have the same styles

### Screenshots

![Screenshot 2023-04-10 at 3 31 16 PM](https://user-images.githubusercontent.com/5090492/230981907-f251d139-900b-4519-8515-06b61119f1d8.png)
![Screenshot 2023-04-10 at 3 30 43 PM](https://user-images.githubusercontent.com/5090492/230981909-8fa483ec-480f-4cbc-9759-3388812ce701.png)

### Operating System (OS)

macOS

**Comment by zeroedin** [comment] 2023-04-10 19:40
Maybe duplicate of: https://github.com/RedHat-UX/red-hat-design-system/issues/896

**Closed** 2023-04-16 16:55 UTC
Labels: bug, documentation
