### ISSUE TITLE
[feat] `<rh-audio-player>` compact/mini size combo to scale and/or scale compact size

### ISSUE THREAD

**Issue by ocean-rh** [RedHat-UX/red-hat-design-system#1260] opened 2023-10-16 20:33 UTC
### Description

`<rh-audio-player>` should be able to scale and not extend past the column it is in. Currently the compact size will only fit in a col-7 or larger and when scaling to smaller sizes it breaks outside of the column. The mini is an option but we need a player that scales that also includes the time stamp. 

### Suggested solution

Nikki mentioned a possibility of making the time bar smaller to keep the sizes of the controls accessible. Or an option of combining the compact size that scales to the mini size on smaller sized screens. But it should not break the column width at any time. 

### Example API

```HTML
<rh-audio-player layout="scalable"></rh-audio-player>
```

### Additional context

<img width="1001" alt="Screenshot 2023-10-16 at 4 32 04 PM" src="https://github.com/RedHat-UX/red-hat-design-system/assets/98612558/01e0bc33-3a23-42ea-a2ba-bd65fd8bec6f">

**Comment by bennypowers** [comment] 2024-09-12 10:28
Closing as a duplicate of https://github.com/RedHat-UX/red-hat-design-system/issues/1264

**Closed by bennypowers** 2024-09-12 10:28 UTC
